### ISSUE TITLE
Question about "Geoclient Issues" on BetaNYC page

### ISSUE THREAD

**Issue by mlipper** [BetaNYC/batch-geocoder-nyc#3]
As the author of Geoclient, I'm curious about the following text on this project's [BetaNYC product page](https://beta.nyc/products/batch-geocoder-for-nyc/):

> In 2019, the DCP’s Planning Labs team created NYC GeoSearch, which provides API to geocode quickly as apposed to GeoClient API which has limitations.

Can you please point me to the link which describes these limitations?

Thanks,
Matt

BTW - Congrats on the new release! I look forward to trying it out.

**Comment by zhik** [comment]
Hey @mlipper,

Sorry if that came off as rude... the limitations I have encountered using GeoClient API is mostly performance and auto search capabilities. It was a great tool for geocoding and more. 

I will correct the text of the product page.

Best,
Zhi

**Comment by zhik** [comment]
Corrected text with 
> ... NYC GeoSearch, which provides API to geocode quickly compared to GeoClient API. _(GeoClient API is still an excellent tool for more advanced functions and has paved the way for accessible geocoding)_ ...

**Comment by mlipper** [comment]
What performance issues did you encounter? Geoclient often processes several million rows per batch on a regular basis. The free public hosted version on the NYC Developer Portal is shared by thousands of distinct client apps and runs on two small AWS/EC2 instances.

Furthermore, it's not actually free. The City has a paid contract which places hard limits the number of requests-per-second and requests-per-day. In other words it's throttled because the City can't afford to pay for unlimited usage.

Geoclient is also Open Source and they are plenty of people who build and run it themselves without any restriction on throughput.
